{{- if and .Values.hugohoster.metrics.enabled .Values.hugohoster.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hugohoster.fullname" . }}
  {{- if .Values.hugohoster.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.hugohoster.metrics.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "hugohoster.labels" . | nindent 6 }}
    {{- with .Values.hugohoster.metrics.serviceMonitor.selector }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.hugohoster.metrics.serviceMonitor.additionalLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}

  {{- with .Values.hugohoster.metrics.serviceMonitor.annotations }}
  annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
spec:
  endpoints:
    - port: {{ .Values.hugohoster.metrics.service.portName }}
      {{- with .Values.hugohoster.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      path: /metrics
      {{- with .Values.hugohoster.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hugohoster.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hugohoster.metrics.serviceMonitor.scheme }}
      scheme: {{ . }}
      {{- end }}
      {{- with .Values.hugohoster.metrics.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "hugohoster.selectorLabels" . | nindent 8 }}
{{- end }}